### ISSUE TITLE
Implement login authentication

### ISSUE THREAD

**Issue by rudwan97** [thecircle-zzm/Backend#8]
- login db
- route
- username
- password  - deprecated
- hashing and salting 
- signature check

jöran en rudwan

> Jöran 13-6-2019 om 13:06
>- Hashing en salting van bcrypt vervangen door eigen algoritme

> Jöran 18-6-2019 om 11:52
>- Password vervangen door signature check

**Comment by voidzero666** [comment]
- [x] Login DB
- [x] UserSchema&Model
- [x] Password hashing and salting

**Comment by voidzero666** [comment]
Crypto functies:
` comparePasswordHash(userpassword, loginUser, session)
sha512 = function (password, salt)
saltHashPassword(userpassword)`

Vervangen door bCrypt algoritme in userSchema:
`userSchema.methods.generateHash = (password) => {
  return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
};`

Salting door rounds of hashing:
`rounds=8 : ~40 hashes/sec
rounds=9 : ~20 hashes/sec
rounds=10: ~10 hashes/sec
rounds=11: ~5  hashes/sec
rounds=12: 2-3 hashes/sec
rounds=13: ~1 sec/hash`
